### ISSUE TITLE
Error: Invalid status code: 400

### ISSUE THREAD

**Issue by pizzafox** [eclass/semantic-release-sentry-releases#144]
Recently started using this and I'm having all the releases fail with a `400` status code.

```js
Error: Invalid status code: 400 
    at ClientRequest.<anonymous> (/home/runner/work/bot/bot/node_modules/@eclass/semantic-release-sentry-releases/src/request.js:101:23)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
```

A `400` would indicate that the data you are sending is invalid or malformed. Can you check that this plugin still works with the current API for releases?

If the plugin is still working properly something must be wrong with my config, which is very basic:
```json
{
	"plugins": [
		[
			"@eclass/semantic-release-sentry-releases",
			{
				"org": "dice",
				"project": "bot",
				"repositoryUrl": "https://github.com/dice-discord/bot"
			}
		]
	]
}
```

**Comment by lgaticaq** [comment]
Hi. you can provide the semantic-release log. To show more info. And check if setted `SENTRY_ORG` or `SENTRY_AUTH_TOKEN` in your CI.

I use the plugin in many projects and it works in all,

**Comment by pizzafox** [comment]
I'm using a config that is only in the environment variables now.
The project, token, and organization variables are all there:

```yaml
SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
SENTRY_PROJECT: bot
SENTRY_ORG: dice
```

Now the error I get is

```js
Check the sentry status (https://status.sentry.io/)

AggregateError: 
    SemanticReleaseError: Error in new release request.
        at module.exports (/home/runner/work/bot/bot/node_modules/@eclass/semantic-release-sentry-releases/src/get-error.js:14:10)
        at module.exports (/home/runner/work/bot/bot/node_modules/@eclass/semantic-release-sentry-releases/src/verify.js:44:13)
    at /home/runner/work/bot/bot/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/runner/work/bot/bot/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/work/bot/bot/node_modules/semantic-release/index.js:94:3)
    at async module.exports (/home/runner/work/bot/bot/node_modules/semantic-release/index.js:259:22)
    at async module.exports (/home/runner/work/bot/bot/node_modules/semantic-release/cli.js:55:5)error Command failed with exit code 1.
```

It might also be worth noting I'm using an integration token for my project instead of a user token. These can be generating at
`https://sentry.io/settings/ORGANIZATION_ID/developer-settings/new-internal/`

**Comment by schw4rzlicht** [comment]
I'm seeing the same issue on an on premises Sentry instance. See logs [here](https://travis-ci.com/github/schw4rzlicht/twitch2ma/builds/171465816).

**Comment by mrlubos** [comment]
Hi, is this still an issue?

**Comment by lgaticaq** [comment]
@pizzafox what permissions does the token you are using have? I use the request `GET https://sentry.io/api/0/organizations/{organization_slug}/` to verify the token and the organization. That is why it is necessary to have the `org:read` permission.

**Comment by pizzafox** [comment]
It looks like I only gave it the permissions for releases and no the organization. I'll try giving it the proper permissions tomorrow. Is it possible to try reading the releases to validate tokens so the only permission it would need is release admin?

![Screenshot_20200828-212402.png](https://user-images.githubusercontent.com/7608555/91628476-e410b600-e974-11ea-9eda-040bf4d44271.png)

**Comment by lgaticaq** [comment]
@pizzafox yes. I am working on that improvement. Thus it will only be necessary to have the release permission.
