### ISSUE TITLE
Fails with code 400

### ISSUE THREAD

**Issue by cxspxr** [eclass/semantic-release-sentry-releases#355]
I have set all the required environment variables, and semantic release creates a release on github, but it doesn't succeed on uploading it to sentry.

.releaserc
```
{
  "branches": [
    {
      "name": "master",
      "prerelease": false
    },
    {
      "name": "staging",
      "prerelease": false,
      "channel": "staging"
    }
  ],
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "angular",
        "releaseRules": [
          {
            "type": "docs",
            "release": "patch"
          },
          {
            "type": "build",
            "release": "minor"
          },
          {
            "type": "refactor",
            "release": "patch"
          },
          {
            "type": "styles",
            "release": "minor"
          },
          {
            "type": "test",
            "release": "patch"
          },
          {
            "type": "ci",
            "release": "minor"
          },
          {
            "type": "revert",
            "release": "minor"
          },
          {
            "type": "chore",
            "release": false
          },
          {
            "type": "perf",
            "release": "minor"
          },
          {
            "type": "fix",
            "release": "patch"
          },
          {
            "type": "feat",
            "release": "minor"
          },
          {
            "scope": "no-release",
            "release": false
          }
        ],
        "parserOpts": {
          "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES"]
        }
      }
    ],
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/github",
      {
        "successComment": false
      }
    ],
    [
      "@eclass/semantic-release-sentry-releases",
      {
        "tagsUrl": "https://github.com/org/repo/tags"
      }
    ]
  ]
}

```

Log output:
```
[11:18:46 AM] [semantic-release] › ℹ  Running semantic-release version 17.2.2
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@eclass/semantic-release-sentry-releases"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@eclass/semantic-release-sentry-releases"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[11:18:48 AM] [semantic-release] › ✔  Run automated release from branch staging on repository https://[secure]@github.com/url-to-repo
[11:18:48 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[11:18:48 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[11:18:48 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[11:18:48 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[11:18:48 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@eclass/semantic-release-sentry-releases"
[11:18:48 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@eclass/semantic-release-sentry-releases"
[11:18:48 AM] [semantic-release] › ℹ  Found git tag v1.0.1 associated with version 1.0.1 on branch staging
[11:18:49 AM] [semantic-release] › ℹ  Found 12 commits since last release
[11:18:49 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1298 from tonydehnke/ci/configurate-each-type-of-commits-for-releases

ci(semantic-release): configure each type of commit to create differe…
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(semantic-release): configure each type of commit to create different releases
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1297 from tonydehnke/ci/sync-semantic-releases-to-sentry

build(sentry): test changed SENTRY_ORG on circleci
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(sentry): test release commit for sentry sync check
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge branch 'staging' into ci/sync-semantic-releases-to-sentry
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(sentry): test changed SENTRY_ORG on circleci
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1295 from tonydehnke/ci/sync-semantic-releases-to-sentry

ci(sentry): sync semantic releases with sentry
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(sentry): sync semantic releases with sentry
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1294 from tonydehnke/chore/change-dependabot-commit-prefix

chore(dependabot): change prefix from chore to build
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(dependabot): change prefix from chore to build
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1293 from tonydehnke/chore/ignore-webpack-cli-dependabot-updates

chore(webpack-cli): ignore updates by dependabot
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(webpack-cli): ignore updates by dependabot
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 12 commits complete: minor release
[11:18:49 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:18:49 AM] [semantic-release] › ℹ  The next release version is 1.1.0
[11:18:49 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[11:18:49 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[11:18:54 AM] [semantic-release] › ✔  Created tag v1.1.0
[11:18:54 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
[11:18:55 AM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github.com/url-to-repo/releases/tag/v1.1.0
[11:18:55 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[11:18:55 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@eclass/semantic-release-sentry-releases"
[11:18:55 AM] [semantic-release] [@eclass/semantic-release-sentry-releases] › ℹ  Retrieving commits data
[11:18:55 AM] [semantic-release] [@eclass/semantic-release-sentry-releases] › ℹ  Commit data retrieved
[11:18:55 AM] [semantic-release] [@eclass/semantic-release-sentry-releases] › ℹ  Creating release 1.1.0
[11:18:55 AM] [semantic-release] [@eclass/semantic-release-sentry-releases] › ✖  Error: Invalid status code: 400 
    at ClientRequest.<anonymous> (/home/circleci/project/node_modules/@eclass/semantic-release-sentry-releases/src/request.js:41:23)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
[11:18:55 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@eclass/semantic-release-sentry-releases"
[11:18:55 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[11:18:58 AM] [semantic-release] [@semantic-release/github] › ℹ  Created issue #1299: https://github.com/tonydehnke/url-to-repo/issues/1299.
[11:18:58 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[11:18:58 AM] [semantic-release] › ✖  ESENTRYDEPLOY Error in new release request.
Check the sentry status (https://status.sentry.io/)

SemanticReleaseError: Error in new release request.
    at module.exports (/home/circleci/project/node_modules/@eclass/semantic-release-sentry-releases/src/get-error.js:14:10)
    at module.exports (/home/circleci/project/node_modules/@eclass/semantic-release-sentry-releases/src/publish.js:105:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async validator (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as publish] (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/index.js:198:20)
    at async module.exports (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/cli.js:55:5) {
  code: 'ESENTRYDEPLOY',
  details: 'Check the [sentry status](https://status.sentry.io/)',
  semanticRelease: true,
  pluginName: '@eclass/semantic-release-sentry-releases'
}[11:18:46 AM] [semantic-release] › ℹ  Running semantic-release version 17.2.2
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@eclass/semantic-release-sentry-releases"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@eclass/semantic-release-sentry-releases"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[11:18:46 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[11:18:48 AM] [semantic-release] › ✔  Run automated release from branch staging on repository https://[secure]@github.com/url-to-repo
[11:18:48 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[11:18:48 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[11:18:48 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[11:18:48 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[11:18:48 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@eclass/semantic-release-sentry-releases"
[11:18:48 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@eclass/semantic-release-sentry-releases"
[11:18:48 AM] [semantic-release] › ℹ  Found git tag v1.0.1 associated with version 1.0.1 on branch staging
[11:18:49 AM] [semantic-release] › ℹ  Found 12 commits since last release
[11:18:49 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1298 from tonydehnke/ci/configurate-each-type-of-commits-for-releases

ci(semantic-release): configure each type of commit to create differe…
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(semantic-release): configure each type of commit to create different releases
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1297 from tonydehnke/ci/sync-semantic-releases-to-sentry

build(sentry): test changed SENTRY_ORG on circleci
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(sentry): test release commit for sentry sync check
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge branch 'staging' into ci/sync-semantic-releases-to-sentry
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(sentry): test changed SENTRY_ORG on circleci
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1295 from tonydehnke/ci/sync-semantic-releases-to-sentry

ci(sentry): sync semantic releases with sentry
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(sentry): sync semantic releases with sentry
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1294 from tonydehnke/chore/change-dependabot-commit-prefix

chore(dependabot): change prefix from chore to build
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(dependabot): change prefix from chore to build
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1293 from tonydehnke/chore/ignore-webpack-cli-dependabot-updates

chore(webpack-cli): ignore updates by dependabot
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(webpack-cli): ignore updates by dependabot
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:18:49 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 12 commits complete: minor release
[11:18:49 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:18:49 AM] [semantic-release] › ℹ  The next release version is 1.1.0
[11:18:49 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[11:18:49 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[11:18:54 AM] [semantic-release] › ✔  Created tag v1.1.0
[11:18:54 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
[11:18:55 AM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github.com/url-to-repo/releases/tag/v1.1.0
[11:18:55 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[11:18:55 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@eclass/semantic-release-sentry-releases"
[11:18:55 AM] [semantic-release] [@eclass/semantic-release-sentry-releases] › ℹ  Retrieving commits data
[11:18:55 AM] [semantic-release] [@eclass/semantic-release-sentry-releases] › ℹ  Commit data retrieved
[11:18:55 AM] [semantic-release] [@eclass/semantic-release-sentry-releases] › ℹ  Creating release 1.1.0
[11:18:55 AM] [semantic-release] [@eclass/semantic-release-sentry-releases] › ✖  Error: Invalid status code: 400 
    at ClientRequest.<anonymous> (/home/circleci/project/node_modules/@eclass/semantic-release-sentry-releases/src/request.js:41:23)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
[11:18:55 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@eclass/semantic-release-sentry-releases"
[11:18:55 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[11:18:58 AM] [semantic-release] [@semantic-release/github] › ℹ  Created issue #1299: https://github.com/url-to-repo/issues/1299.
[11:18:58 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[11:18:58 AM] [semantic-release] › ✖  ESENTRYDEPLOY Error in new release request.
Check the sentry status (https://status.sentry.io/)

SemanticReleaseError: Error in new release request.
    at module.exports (/home/circleci/project/node_modules/@eclass/semantic-release-sentry-releases/src/get-error.js:14:10)
    at module.exports (/home/circleci/project/node_modules/@eclass/semantic-release-sentry-releases/src/publish.js:105:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async validator (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as publish] (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/index.js:198:20)
    at async module.exports (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/circleci/.npm/_npx/255/lib/node_modules/semantic-release/cli.js:55:5) {
  code: 'ESENTRYDEPLOY',
  details: 'Check the [sentry status](https://status.sentry.io/)',
  semanticRelease: true,
  pluginName: '@eclass/semantic-release-sentry-releases'
}
```

**Comment by lgaticaq** [comment]
Hi @cxspxr. The environment variables `SENTRY_PROJECT`, `SENTRY_ORG` and `SENTRY_AUTH_TOKEN` are setted in your CI?

**Comment by cxspxr** [comment]
Yes, all three are set

**Comment by sashahilton00** [comment]
I also have this issue. Environment variables are set, yet hitting a 400 bad request when trying to publish. Have also verified that the scopes are correct for the auth token.

**Comment by robotjonez** [comment]
Hello! So we are currently trying to utilize this tool in our project here at Cisco and we are also experiencing this issue...We have verified our CI/CD (SENTRY_PROJECT, SENTRY_URL, SENTRY_ORG, and SENTRY_AUTH_TOKEN) environment variables are correct, I have attached an image of the log. 

![Screen Shot 2021-06-13 at 7 07 55 PM](https://user-images.githubusercontent.com/26654215/121825980-f5fce480-cc7a-11eb-9948-4b9403dcdf90.png)

I will note that I have no issue manually creating a release via the CURL command using the same environment variable values.
![Screen Shot 2021-06-13 at 7 15 23 PM](https://user-images.githubusercontent.com/26654215/121826116-c6021100-cc7b-11eb-955e-f9691208bbeb.png)

Any help would be greatly appreciated!

**Comment by schp** [comment]
For us the 400 error was caused by the fact that Sentry limits the length of the repositoryUrl field to 64 characters. Of course it would be helpful if the plugin would display the actual error message returned by Sentry in addition to the HTTP status code.
